name: "test-functions"

on:
    push: #trigger on push
    workflow_dispatch: #manual trigger

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: "first-step"
              run: echo "this is a test"
            - name: "sleep-5"
              run: sleep 5 #sleeps the job for specified amount (5)
            - name: "second-step"
              run: exit 1
            - name: "unreachable-step"
              if: ${{ success() }}
              run: echo "this will never happen"
            - name: "always-runs"
              if: ${{ always() }}
              run: echo "this step will run"
