name: "test-functions"

on:
    push:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: "first-step"
              run: echo "this is a test"
            - name: "second-step"
              run: exit 1
            - name: "unreachable-step"
              if: ${{ success() }}
              run: echo "this will never happen"
